Enable payloads for factory interceptors. Add test for that.
Join templates for interceptors of all types into one dir.

diff --git a/sources/examples/file_access_counter/tests/test.sh.in b/sources/examples/file_access_counter/tests/test.sh.in
--- a/sources/examples/file_access_counter/tests/test.sh.in
+++ b/sources/examples/file_access_counter/tests/test.sh.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # Only check that example can be built.
-if ! make -C @example_dir@; then
-    printf "Failed to build example.\n"
+if ! make -C @example_dir@ clean all; then
+    printf "Failed to (re)build example.\n"
     exit 1
 fi
diff --git a/sources/examples/read_counter/tests/test.sh.in b/sources/examples/read_counter/tests/test.sh.in
--- a/sources/examples/read_counter/tests/test.sh.in
+++ b/sources/examples/read_counter/tests/test.sh.in
@@ -16,8 +16,8 @@ unload_all()
     /sbin/rmmod ${kedr_coi_module}
 }
 
-if ! make -C @example_dir@; then
-    printf "Failed to build example.\n"
+if ! make -C @example_dir@ clean all; then
+    printf "Failed to (re)build example.\n"
     exit 1
 fi
 
