'use_copy' and 'at_place' replacement mechanisms are now selected at runtime, according to pointer to the operations. API has slightly changed: Additional functions are introduced for set 'trace_unforgotten_object' callback and replacement mechanism selector for already created interceptors. jinja2-yaml template generator instead of kedr_gen is used now.
Tests has been updated for use new API. They pass now.

kmodule_configure_operations() CMake function has been developed for simplify configuration of operations set(with types).
Possible set of operations has been updated for work on Linux kernel 3.14(TODO: intercept new functions).

diff --git a/sources/examples/read_counter/tests/test.sh.in b/sources/examples/read_counter/tests/test.sh.in
--- a/sources/examples/read_counter/tests/test.sh.in
+++ b/sources/examples/read_counter/tests/test.sh.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 sample_target_name="@module_name@"
-sample_target_script="sh @CMAKE_CURRENT_BINARY_DIR@/kedr_sample_target"
+sample_target_script="sh @CMAKE_CURRENT_BINARY_DIR@/@example_dir@/kedr_sample_target"
 
 kedr_coi_module="@CMAKE_BINARY_DIR@/core/kedr_coi.ko"
 
@@ -15,6 +15,12 @@ unload_all()
     ${sample_target_script} unload
     /sbin/rmmod ${kedr_coi_module}
 }
+
+if ! make -C @example_dir@; then
+    printf "Failed to build example.\n"
+    exit 1
+fi
+
 
 if ! /sbin/insmod ${kedr_coi_module}; then
     printf "Failed load KEDR COI core module into kernel.\n"
